### ISSUE TITLE
[Feature] Unify json parser

### ISSUE THREAD

**Issue by simon824** [apache/seatunnel#1091]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Unify json parser, replace fastjson with jackson.
Now both fastjson and jackson exist in seatunnel.

![image](https://user-images.githubusercontent.com/18065113/149931583-81e90cfc-3a6e-4703-ad8e-91574147bac0.png)

![image](https://user-images.githubusercontent.com/18065113/149931609-adbeb804-0778-4902-913f-7a471feb2647.png)

### Task list
- #1173 @simon824 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
