### ISSUE TITLE
[Umbrella] Optimize checkConfig

### ISSUE THREAD

**Issue by simon824** [apache/seatunnel#1153]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

This umbrella issue is used to optimize redundant code in `checkConfig`
 
We introduce `CheckConfigUtil` to optimize redundant code in `checkConfig`, included checkAllExists() , checkAtLeastOneExists(), mergeCheckResults()

### Task list

- [x] #1117 
- [x] #991 
- [x] #1133 
- [ ] #1152 
- [ ] #1136 
- [ ] #1154 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
