### ISSUE TITLE
[Feature][Connector] Clickhouse-File performance boost 

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#1513]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

In order to improve the code quality and performance of ClickhouseFile Sink, the following work needs to be done. First version is #1501 . Design in #1382 

### Task list

- [ ] Support Rsync to transfer clickhouse data file
- [ ] Support zero copy to boost file transfer performance
- [x] Change data stream from echo command to file stream #1566 
- [ ] Exactly-Once support

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Emor-nj** [comment]
@Hisoka-X  Can i import the project [rsync4j](https://github.com/fracpete/rsync4j) to support Rsync to transfer clickhouse data file?

**Comment by Hisoka-X** [comment]
> @Hisoka-X Can i import the project [rsync4j](https://github.com/fracpete/rsync4j) to support Rsync to transfer clickhouse data file?

Hi, of course. Welcome to contribute this feature!
