### ISSUE TITLE
[Umbrella] Refactor the Flink batch api

### ISSUE THREAD

**Issue by 1996fanrui** [apache/seatunnel#1727]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Currently, Flink use the DataStream api to process stream and batch, and Flink recognizes stream or batch by `env.setRuntimeMode(final RuntimeExecutionMode executionMode)`. Seatunnel still use DataSet api to process batch, could we refactor the FlinkBatchExecution and related code? 

Benefits:

- The DataSet has deprecated, some optimizations of the Flink new version only apply to DataStream api.
- The Transform Plugin will be easier, we just implement the `processStream(FlinkEnvironment env, DataStream<Row> dataStream)`
- Currently, all Transform Plugins implement the `setConfig` and `getConfig`. After refactor, we will change the FlinkStreamTransform from interface to abstract class. It can greatly reduce the duplication of code

Actually, I'm a new user of Seatunnel, I might miss some benefits, you can add it in the comment.

### Task list

I have read some Seatunnel code and I found that Seatunnel code is easy to refactor. But there are too many sources or sinks. So I suggest that we refactor these through some subtasks, and I also hope that friends who are familiar with the related Source and Sink will participate. We make sure that Seatunnel connectors are as efficient as possible.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 1996fanrui** [comment]
I think this issue is a duplicate of #1246 , so I closed it.
