### ISSUE TITLE
[Umbrella] Support Spark-3.3.x

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#2327]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Support Spark-3.3.x

### Task list

- [x] https://github.com/apache/incubator-seatunnel/issues/2248#issue-1315476987
- [x] https://github.com/apache/incubator-seatunnel/issues/2328#issue-1324602745

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
