### ISSUE TITLE
[Umbrella] Improved build and e2e test

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2604]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

We expect to improve many issues with seatunnel when building and doing e2e test.

### Task list

- [x] #2599 @ashulin 
- [x] #2600 @ashulin 
- [x] #2605 
- [x] #2606
- [x] #2607 @hailin0
- [x] #2673 @ashulin 
- [x] #2681

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
