### ISSUE TITLE
[Discuss][RoadMap] SeaTunnel RoadMap

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2729]
Hi everyone.
Here we can discuss the roadmap of SeaTunnel in Q4.

### SeaTunnel API & SeaTunnel Connector
- [x] CDC Connector MySQL https://github.com/apache/incubator-seatunnel/issues/2394
- [x] Transform API https://github.com/apache/incubator-seatunnel/issues/2678
- [x] Transform V2 Flink Translation https://github.com/apache/incubator-seatunnel/issues/3267
- [x] Transform V2 Spark Translation https://github.com/apache/incubator-seatunnel/issues/3268
- [ ] Database Synchronization Connector (batch mode)
- [ ] More Source & Sink & Transform Connector https://github.com/apache/incubator-seatunnel/issues/3018
- [ ] Support Connector Metrics
- [ ] Support TableSourceFactory and can get the Connector Option Rules.
- [ ] Support TableSinkFactory and can get the Connector Option Rules.

### SeaTunnel Web Server
submodule: https://github.com/apache/incubator-seatunnel-web
- [x] #3374 
- [ ] Release MVP version, and improve the fellings.

### SeaTunnel Engine
- [x] Release MVP version
- [x] Support Transform Action
- [x] Support EventType API(For CDC connector we need know `Update`/`Insert`/`Delete` type)
- [ ] Run on k8s
- [x] Performance testing & Performance optimization
- [ ] Support IMap Storage By JDBC #3870
- [x] #3871

### Spark/Flink new version support

- [x]  #2733
- [x] Support Spark3 https://github.com/apache/incubator-seatunnel/issues/2189
- [x] Support Flink 1.15.X https://github.com/apache/incubator-seatunnel/issues/2927

### CDC
- [ ] https://github.com/apache/incubator-seatunnel/issues/4605
- [x] https://github.com/apache/incubator-seatunnel/issues/4604

**Comment by ashulin** [comment]
Improve end-to-end testing of connector-v2 in a multi-engine environment;
Now developers need to write a lot of repeated code to test different engines, if we support more version engine, this will generate more repeated test code;

**Comment by dijiekstra** [comment]
SeaTunnel Web Server:
Release MVP version, and improve the fellings.

**Comment by EricJoy2048** [comment]
@ashulin  @CalvinKirs  How about storage Snapshot by JDBC?

**Comment by liugddx** [comment]
Support Flink 1.15.X #2927

**Comment by MonsterChenzhuo** [comment]
`Run on k8s` is anyone working on this, if not, I think I can make it happen

**Comment by cason0126** [comment]
**Support Cache between source and sink**
What are the requirements for this feature ？
up to now ， ST Connector is mostly BatchMode ,Is this Feature for in case Sink Speed Less Than Source？
if so， Control Source Speed can solve it with low memory use。
@EricJoy2048

**Comment by CalvinKirs** [comment]
> `Run on k8s` is anyone working on this, if not, I think I can make it happen

Not yet, welcome you contribute it

**Comment by 2000liux** [comment]
Is there a todolist item in Transform V2 Flink Translation? I can do something related。
@EricJoy2048

**Comment by jobmission** [comment]
@EricJoy2048  long time no updates?

**Comment by somnmos** [comment]
how about to support multi-source and complex query sql plugin in zeta engine?
