### ISSUE TITLE
[Improve][Connector-V2-kafka] Imporve kafka connector

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2755]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Imporve kafka connector features & bugs

### Task list

Bugs:
- [x] #2754

Features:

Common
- [x] #2840 
- [ ] Add e2e testcase
- [ ] Support kafka-to-kafka raw message extract & load(high performance)

Sink
- [x] #2786
- [x] #2787
- [ ] Support more  formats for message(json、csv、...)
- [ ] Support write message metadata(key、timestamp、headers)

Source
- [ ] Support define schema & format
- [ ] Support for dynamic discover `topic` & `partition` in streaming mode
- [ ] Support setting read starting offset or time at startup config
- [ ] Support read message metadata(key、timestamp、headers)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hailin0** [comment]
Anyone willing to help?

**Comment by TaoZex** [comment]
I would like to try the following two tasks:
1.Support extract topic from SeaTunnelRow fields
2.Support extract partition from SeaTunnelRow fields
The two tasks are relatively similar, so I want to do them together. Could you assign it to me? Plz~

**Comment by TaoZex** [comment]
https://github.com/apache/incubator-seatunnel/issues/2786 What function does this issue want to achieve?

**Comment by Carl-Zhou-CN** [comment]
I want to try the following three tasks：
 Support for dynamic discover topic & partition in streaming mode
 Support setting read starting offset or time at startup config
 Support read message metadata(key、timestamp、headers)

**Comment by EricJoy2048** [comment]
> I want to try the following three tasks： Support for dynamic discover topic & partition in streaming mode Support setting read starting offset or time at startup config Support read message metadata(key、timestamp、headers)

Thx for your contribution. Please create issues and link this page.

**Comment by TaoZex** [comment]
I would like to finish the following two tasks:
 Support more formats for message(json、csv、...)
 Support write message metadata(key、timestamp、headers)
Please assign it to me? thx.

**Comment by hailin0** [comment]
> I would like to finish the following two tasks: Support more formats for message(json、csv、...) Support write message metadata(key、timestamp、headers) Please assign it to me? thx.

Thx for your contribution. Please create issues and link this page.

**Comment by Carl-Zhou-CN** [comment]
I want to try the following three tasks：
Add e2e testcase
