### ISSUE TITLE
[Improve][Connector-V2] Imporve mongodb connector

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2790]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Imporve mongodb connector.

Anyone willing to help?

### Task list

Features:

Sink
- [ ] Support extract `database`、`collection` from SeaTunnelRow fields
- [ ] Support `EXACTLY_ONCE`
- [ ] Support [bulkWrite](https://www.mongodb.com/docs/drivers/java/sync/current/usage-examples/bulkWrite/)

Source
- [ ] Support for filter at find documents
- [ ] Supports parallelism reads using partition
- [ ] Support `EXACTLY_ONCE` & restore state

BUG:

- [ ] Spark IT exception in JRE11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hailin0** [comment]
@TyrantLucifer 

Please help to add `help wanted` label

**Comment by hailin0** [comment]
subtask #2778

**Comment by EricJoy2048** [comment]
@hailin0  What is the status of this issue?

**Comment by MonsterChenzhuo** [comment]
@EricJoy2048  I have done some related work #3698 
please assign to me; thx。

**Comment by MonsterChenzhuo** [comment]
@EricJoy2048  #2790 I have done some related work。Soon I will make a contribution
