### ISSUE TITLE
[Feature][core] Add meta info to each SeatunnelRow

### ISSUE THREAD

**Issue by lhyundeadsoul** [apache/seatunnel#2915]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In some connector(e.g. TDengine), there are some meta info should be transferred from `source` to `sink` (e.g. sub-table-name/ tags) which are different from each data. 
Nevertheless, there is still no native and generic solution for this in Seatunnel. 

Some alternatives here to be considered:

- [ ] org.apache.seatunnel.api.table.catalog.Column.MetadataColumn
- [ ] org.apache.seatunnel.api.table.connector.SupportReadingMetadata

### Usage Scenario

In TDengine Source:
source data doesn't have tags and sub-table-name which are important to TDengine Sink to write data.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@ashulin  What do you think about it?

**Comment by ashulin** [comment]
MetadataColumn and SupportReadingMetadata are indeed designed to solve this problem, but it has not been completed yet, and some pre-problems need to be solved；
#2490
