### ISSUE TITLE
[Umbrella][doc] improve document

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2973]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

During the release of 2.2.0-beta, I found many problems in the current document. I hope we can improve it.

I found something that could be improved:

1. The seatunnel version in the document needs to be manually modified, which is easy to forget
2. The Chinese document is now unmaintained, but it is still in the code repository
3. Part of the document is missing and has not been completed
4. The documents for V2 are not differentiated from those for V1, and much of V2's feature(data type, format, catalog, etc) documentation is also missing.

### Task list

- Script used to update the seatunnel version in doc
- #2972
- Completion documents
- Optimized the document switchover between V1 and V2
- starter v2 doc error in website #2991

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by EricJoy2048** [comment]
@hailin0  PTAL
