### ISSUE TITLE
[Umbrella] [Dirty data] This is new feature for dirty data

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3002]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Dirty data is data that is not meaningful to the business, has an illegal format, or is out of sync. A single piece of data is dirty if an exception occurs during writing to the target data source. So any data that fails to write is classified as dirty. For example, data of type VARCHAR on the source side is written to the target column of type INT, resulting in data that can not be written because of improper conversion. You can control whether dirty data is allowed during synchronization when task configuration is synchronized, and support for controlling the number of dirty data bars, that is, when the dirty data exceeds the specified number, the task fails to exit.

### Task list

Support for defining dirty data and its impact on tasks

- [ ]  When do not allow the dirty data, if produce dirty data synchronization task execution process, the task will fail
- [ ] When allowing dirty data and set its threshold, synchronization task will ignore the dirty data (that is, won't write to the target side), and normal execution.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by Hisoka-X** [comment]
Can you show me how to achieve this feature？

**Comment by liugddx** [comment]
> Can you show me how to achieve this feature？

I will output the detailed design later

**Comment by iture123** [comment]
It would be better if it could support specified tolerance ratio of the dirty data.

**Comment by liugddx** [comment]
> It would be better if it could support specified tolerance ratio of the dirty data.
Now is not good support and need to provide the collector features first.

**Comment by liugddx** [comment]
#3431

**Comment by liugddx** [comment]
flink:https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/ops/metrics/
spark:https://spark.apache.org/docs/2.4.5/rdd-programming-guide.html#shared-variables

**Comment by Hisoka-X** [comment]
>  When allowing dirty data and set its threshold, synchronization task will ignore the dirty data (that is, won't write to the target side), and normal execution.

If we want achieve this feature, two way: 1. the sink connector should make sure they are not throw exception when meet dirty data. 2. Or we recreate sink connector again. 
Both have some problem, 1 will be hard to do with all connector, 2 will have many connection to create and close.

**Comment by liugddx** [comment]
> > When allowing dirty data and set its threshold, synchronization task will ignore the dirty data (that is, won't write to the target side), and normal execution.
> 
> If we want achieve this feature, two way: 1. the sink connector should make sure they are not throw exception when meet dirty data. 2. Or we recreate sink connector again. Both have some problem, 1 will be hard to do with all connector, 2 will have many connection to create and close.

I think you can use the first way.Whether can be obtained at a higher level anomalies and then use the accumulator?
