### ISSUE TITLE
[Umbrella][Code Style] Automatic log object generation using lombok annotations

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3003]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

According to the community specification, code development prefers to use the lombok plugin, so we need to use the lombok plugin's annotations to replace the previous code segment.

### Task list

There ars some sub-tasks as the following:

- [ ] seatunnel-api
- [ ] seatunnel-apis
- [ ] seatunnel-common
- [ ] seatunnel-connectors
- [ ] seatunnel-connectors-v2
- [ ] seatunnel-core
- [ ] seatunnel-e2e
- [ ] seatunnel-engine
- [ ] seatunnel-examples
- [ ] seatunnel-formats
- [ ] seatunnel-plugin-discovery
- [ ] seatunnel-transforms
- [ ] seatunnel-translation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
