### ISSUE TITLE
[Feature][Connector-V2] Imporve iotdb connector

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3012]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Imporve iotdb connector.

### Task list

Common:
- [ ] Unified configuration property names and formats

Source:
- [ ]  Support read [`VECTOR`](https://github.com/apache/iotdb/blob/v0.13.2/tsfile/src/main/java/org/apache/iotdb/tsfile/utils/TsPrimitiveType.java#L49) datatype
- [ ] Support read [tsfile](https://iotdb.apache.org/UserGuide/Master/API/Programming-TsFile-API.html)

Sink：
- [ ]  Support write [`VECTOR`](https://github.com/apache/iotdb/blob/v0.13.2/tsfile/src/main/java/org/apache/iotdb/tsfile/utils/TsPrimitiveType.java#L49) datatype
- [ ] Support write [tsfile](https://iotdb.apache.org/UserGuide/Master/API/Programming-TsFile-API.html)
- [ ] Support write tsfile load into iotdb server.[reference1](https://iotdb.apache.org/UserGuide/V0.13.x/Write-And-Delete-Data/Load-External-Tsfile.html#introduction),[reference2](https://mp.weixin.qq.com/s/nrns7BYktyZR3tNawvMNTg)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hailin0** [comment]
Anyone willing to help?

**Comment by hailin0** [comment]
Please help to add `help wanted` label
