### ISSUE TITLE
[Umbrella] Extract format conversion module.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3120]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

 Extract format conversion module,parquet Avro and ORC .

### Task list

 Extract format conversion module,parquet Avro and ORC .
- [ ] parquet .
- [ ] Avro.
- [ ] ORC.
- [ ] CSV.
- [ ] PROTOBUF.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by liugddx** [comment]
Is this mission necessary? @EricJoy2048 @hailin0 @ashulin @CalvinKirs @Hisoka-X @TyrantLucifer

**Comment by TyrantLucifer** [comment]
Currently orc and parquet are tightly bound to the writer and reader, extracting the module can not be reused, the matter is meaningless, the ability to parse csv has been implemented in format-text, for avro and protobuf, there are currently connectors need to use this ability?

**Comment by liugddx** [comment]
> Currently orc and parquet are tightly bound to the writer and reader, extracting the module can not be reused, the matter is meaningless, the ability to parse csv has been implemented in format-text, for avro and protobuf, there are currently connectors need to use this ability?

Using `hudi-java-client` seem to read or write hudi requires avro format.

**Comment by TaoZex** [comment]
> Currently orc and parquet are tightly bound to the writer and reader, extracting the module can not be reused, the matter is meaningless, the ability to parse csv has been implemented in format-text, for avro and protobuf, there are currently connectors need to use this ability?

We need avro format for read debezium message. Please see this issue:
https://github.com/apache/incubator-seatunnel/issues/3743
