### ISSUE TITLE
[Umbrella][Web] Add a DataSource Management Services

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3180]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We need a DataSource Management Service, It will have some features:

1. All DataSource Information will manage in this service. And the service provides an SDK to provide data source information to other services.
2. For JDBC DataSource, it will support jdbc connector information config and test. And it need support get table list and fields about the database.
3. For API DataSource, it will support define `api_name` `api_url` and `api_schema`. Some times token may be need.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
IMO, add a catalog storage to save the **options** of the [CatalogFactory](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-api/src/main/java/org/apache/seatunnel/api/table/factory/CatalogFactory.java)

We can directly use CatalogFactory to verify the correctness of the options

**Comment by MonsterChenzhuo** [comment]
@EricJoy2048  please assign to me; thx。
