### ISSUE TITLE
[Umbrella][flink] Upgrade flink

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3263]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I think flink upgrade needs to be upgraded gradually.Every major version changes a lot
,so need to upgrade from 1.13 to 1.14 and then to 1.15.Here's what to look for in an upgrade.If there is anything that needs attention, please reply in the issue,thanks.
- [ ] [https://nightlies.apache.org/flink/flink-docs-release-1.13/release-notes/flink-1.14](upgrade 1.14) #3468 
- [ ] [https://nightlies.apache.org/flink/flink-docs-release-1.13/release-notes/flink-1.15/](upgrade 1.15)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Now that we have removed all the code of the V1 version, I can continue to upgrade flink.

**Comment by liugddx** [comment]
There are two options for upgrading flink:

1.Build the starter by module, such as seatunnel-flink-starter-v13, seatunnel-flink-starter-v14.
2.When packaging, put all the multi-version packages of flink in /seatunnel/starter.
3.Load the corresponding starter according to different flink versions when submitting tasks.

Advantage:
You can deploy only one seatunnel application, and submit tasks to different flinks by setting environment variables of different versions of flinks. This is imperceptible to the user.

-- 


1.Build the starter by module, such as seatunnel-flink-starter-v13, seatunnel-flink-starter-v14.
2.Only build the corresponding version of flink with the -Dflink.version build parameter.

Advantage:
Reduce the size of the installation package, relatively lightweight.

**Comment by liugddx** [comment]
> There are two options for upgrading flink:
> 
> 1.Build the starter by module, such as seatunnel-flink-starter-v13, seatunnel-flink-starter-v14. 2.When packaging, put all the multi-version packages of flink in /seatunnel/starter. 3.Load the corresponding starter according to different flink versions when submitting tasks.
> 
> Advantage: You can deploy only one seatunnel application, and submit tasks to different flinks by setting environment variables of different versions of flinks. This is imperceptible to the user.
> 
> --
> 
> 1.Build the starter by module, such as seatunnel-flink-starter-v13, seatunnel-flink-starter-v14. 2.Only build the corresponding version of flink with the -Dflink.version build parameter.
> 
> Advantage: Reduce the size of the installation package, relatively lightweight.

@Hisoka-X @EricJoy2048 @hailin0 @TyrantLucifer @ashulin @ic4y @CalvinKirs

**Comment by TyrantLucifer** [comment]
> > There are two options for upgrading flink:
> 
> > 
> 
> > 1.Build the starter by module, such as seatunnel-flink-starter-v13, seatunnel-flink-starter-v14. 2.When packaging, put all the multi-version packages of flink in /seatunnel/starter. 3.Load the corresponding starter according to different flink versions when submitting tasks.
> 
> > 
> 
> > Advantage: You can deploy only one seatunnel application, and submit tasks to different flinks by setting environment variables of different versions of flinks. This is imperceptible to the user.
> 
> > 
> 
> > --
> 
> > 
> 
> > 1.Build the starter by module, such as seatunnel-flink-starter-v13, seatunnel-flink-starter-v14. 2.Only build the corresponding version of flink with the -Dflink.version build parameter.
> 
> > 
> 
> > Advantage: Reduce the size of the installation package, relatively lightweight.
> 
> 
> 
> @Hisoka-X @EricJoy2048 @hailin0 @TyrantLucifer @ashulin @ic4y @CalvinKirs 

This task I had designed the solution， we can discuss it in meetup   next Tuesday
