### ISSUE TITLE
[Umbrella][Improve][Connector] Provide test cases for `exactly-once`.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3754]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now there are many source connectors that support `exactly-once`, but there is no test case to test it. So I suggest to provide a test case to test this function, you can refer to #3637.

It is necessary to ensure that the checkpoint of the task is turned on.

step1: Start the corresponding application and initialize enough data, generally more than 1000.
step2: Start the `seatunnelServer` and check that the task status is running.
step3: Stop `seattunnelServer`.
step4: Start `seatunnelServer` and wait for task execution to complete.
step5: Check result data.

- [x] [Improve][Engine][Connector-V2][Fake] Support engine restart job information will not be lost and make sure exactly-once is ok #3637
- [x] #3759
- [x] #3758
- [x] #3757
- [x] #3761
- [x] #3766
- [x] #3762
- [x] #3763
- [x] #3764
- [x] #3765

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
That's great.

It's also very meaningful.

**Comment by liugddx** [comment]
I have three options here, 

1. the first is to write use cases directly behind `ClusterFaultToleranceIT`. 
2. The second is to add verification to our e2e. 
3. The third is to add test cases to the `connector-console-seatunnel-e2e` module.

The first solution needs to start the third-party application separately, which is more troublesome to implement and will lead to code redundancy.
The second solution is currently disabled due to the engine's e2e, so pass it temporarily.
The third solution is the most suitable solution at present, but there are also cases where third-party applications are activated, which will lead to certain resource occupation


So please give me some advice.

**Comment by liugddx** [comment]
> I have three options here,
> 
> 1. the first is to write use cases directly behind `ClusterFaultToleranceIT`.
> 2. The second is to add verification to our e2e.
> 3. The third is to add test cases to the `connector-console-seatunnel-e2e` module.
> 
> The first solution needs to start the third-party application separately, which is more troublesome to implement and will lead to code redundancy. The second solution is currently disabled due to the engine's e2e, so pass it temporarily. The third solution is the most suitable solution at present, but there are also cases where third-party applications are activated, which will lead to certain resource occupation
> 
> So please give me some advice.

@EricJoy2048 @ic4y @hailin0 @TyrantLucifer @ashulin

**Comment by ic4y** [comment]
SavePoint is supported in #3779, I think it is more appropriate to use savePoint to stop the job and restore with savepoint it to test exactly-once

**Comment by liugddx** [comment]
> 

Great advice, i will try it after this pr is merged.
