### ISSUE TITLE
[Umbrella][Feature][Connector-V2] Support config check function

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3952]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

As we know, we had done the work of upgrading connector v2, but some features also did't be developed. So in this issue we will do the implementation of config check logic.

There are the following steps to do this task:

1. Add check logic in `Plugin#prepare`
2. Add unit test in connectors

You can refet to #3953 study the fake connector example.

### Task list

- [x] #3953 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TyrantLucifer** [comment]
This task will start after #3800 #3947 merged.
