### ISSUE TITLE
[Umbrella][Feature][Connector-V2] Support savemode for sink connectors

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3954]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

This issue will do the work about supporting savemode feature for sink connectors. You can see all the design at #3824 

### Task list

- [x] #3965
- [x] #3966

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TyrantLucifer** [comment]
This task will start after #3885 merged.
