### ISSUE TITLE
[Umbrella][Feature][Core] Support flink 1.15.x and 1.16.x

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3964]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

After had been done the work about refactor starter, we can start the process of upgrading flink version.

The whole is broken down into the following steps:

1. Create new starter module
2. Create new flink translation layer

Different version starter and translation layer will be packaged in different jar. The shell script distinguishes which jar to run.

![drawio](https://user-images.githubusercontent.com/51053924/212891841-e4928497-6532-43e3-9551-3965f920822e.png)

### Task list

- [ ] Develop new starter module
- [ ] Develop flink translation layer using new flink api

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by liugddx** [comment]
#3263

**Comment by 2000liux** [comment]
@liugddx  you are too fast。
