### ISSUE TITLE
[Umbrella] Enrich Catalog

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#4093]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

This Issue contains some task to enrich catalog.

### Task list

- [x] https://github.com/apache/incubator-seatunnel/issues/4092
- [x] https://github.com/apache/incubator-seatunnel/issues/4102
- [x] https://github.com/apache/incubator-seatunnel/issues/4103
- [x] https://github.com/apache/incubator-seatunnel/issues/4104

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
