### ISSUE TITLE
[Umbrella] [Zeta] [REST-API] Provide rest api for zeta

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#4143]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Currently Zeta has provided  rest api, see this for details #4044. Now we need to expose more capabilities via rest.

### Task list

- [x] Get all running job info. #4072 
- [x] Get running job info by jobId. #4140 
- [x] #4144
- [x] #4145
- [x] #4146
- [x] #4416
- [x] #4417
- [ ] etc ...

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by liugddx** [comment]
You can reach me for any questions. My WeChat ID is liuggdx.

**Comment by FlechazoW** [comment]
I am happy to help.

**Comment by liugddx** [comment]
> I am happy to help.

Please reply under issue.

**Comment by Zzihh** [comment]
maybe i want to try.

**Comment by liugddx** [comment]
> maybe i want to try.

Please reply under the issue you are interested in, and you can reach me for any questions. My WeChat ID is liuggdx.

**Comment by liugddx** [comment]
> I am happy to help.

What's the progress? Let me know if you need anything.

**Comment by liugddx** [comment]
> maybe i want to try.

What's the progress? Let me know if you need anything.

**Comment by MonsterChenzhuo** [comment]
[Feature][Zeta][REST-API] Submit a job.
[Feature][Zeta][REST-API] Stop a running job.
@liugddx These two please assign to me; thx。

**Comment by liugddx** [comment]
> [Feature][Zeta][REST-API] Submit a job. [Feature][Zeta][REST-API] Stop a running job. @liugddx These two please assign to me; thx。

Please reply under the corresponding issue.

**Comment by MonsterChenzhuo** [comment]
@liugddx  I want to add two api issues:
add shuts down the cluster
add returns the cluster configuration.

**Comment by liugddx** [comment]
> @liugddx I want to add two api issues: add shuts down the cluster add returns the cluster configuration.

I think we can add. @EricJoy2048 @hailin0 @TyrantLucifer @Hisoka-X
