### ISSUE TITLE
[Umbrella][Spark][E2E] Enable spark e2e test cases of connectors

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#4356]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Currently, SeaTunnel has completed end-to-end testing for Flink versions 1.13-1.16 in terms of construction.

However, in the case of the Spark engine, some connectors' built-in dependencies conflict with certain dependencies of Spark, causing e2e testing of these connectors to fail in Spark.

In order to ensure the stability of the connectors, we need to solve these issues.

For more error details, you can refer to https://github.com/apache/incubator-seatunnel/pull/4286

**Tips: This problem can be solved with `maven-shade` plugin.**

### Task list

- [ ] ES Connector
- [ ] Http Connector
- [ ] Amazon Dynamo DB Connector
- [ ] Jdbc Connector
- [ ] Clickhouse Connector
- [ ] Neo4j Connector

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MonsterChenzhuo** [comment]
ES、Clickhouse、Amazon Dynamo DB、Neo4j please assign to me; thx。

**Comment by FlechazoW** [comment]
Http and jdbc, please.

**Comment by TyrantLucifer** [comment]
#4534 is merged, this task has been done.
