### ISSUE TITLE
[Umbrella] Catalog supports multiple tables

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#4528]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Backgroud & Motivation

When the current job supports multi-table reading, use Catalog in JobConfigParser to get the CatalogTable list.

The above scheme leads to some problems:

- The acquisition of each CatalogTable needs to obtain and close the Connection, and the connection consumption is high;

- The acquisition logic is fixed in JobConfigParser, which cannot support the differentiation of each Catalog acquisition list;

Based on the above problems, this proposal hopes to allow Catalog to support the acquisition of CatalogTable list, so as to achieve:

- Support multiplexing connections;

- Customize logic by Catalog;

### Proposed Changes

- Add `#getTables` method;

- Open reusable resources in the `#open()` method;

- After the catalog is used, call `#close()` to close the resource;

```Java

 //pseudocode
 package org.apache.seatunnel.api.table.catalog;
 ​
 public interface Catalog {
     // ...
     List<CatalogTable> getTables(ReadonlyConfig config) throws CatalogException, TableNotExistException;
      
     void open() throws CatalogException;
 ​
     void close() throws CatalogException;
 }

```

- Remove `CatalogTableUtil#getCatalogTables()` method

```Java

//pseudocode
 package org.apache.seatunnel.api.table.catalog;
 ​
 public class CatalogTableUtil implements Serializable {
      
    public static List<CatalogTable> getCatalogTables(
             ReadonlyConfig catalogConfig, Catalog catalog) {
         // Get the list of specified tables
         List<String> tableNames = catalogConfig.get(CatalogOptions.TABLE_NAMES);
         List<CatalogTable> catalogTables = new ArrayList<>();
         if (tableNames != null && tableNames.size() >= 1) {
             for (String tableName : tableNames) {
                 catalogTables.add(catalog.getTable(TablePath.of(tableName)));
             }
             return catalogTables;
         }
 ​
         // Get the list of table pattern
         String tablePatternStr = catalogConfig.get(CatalogOptions.TABLE_PATTERN);
         if (StringUtils.isBlank(tablePatternStr)) {
             return Collections.emptyList();
         }
         Pattern databasePattern =
                 Pattern.compile(catalogConfig.get(CatalogOptions.DATABASE_PATTERN));
         Pattern tablePattern = Pattern.compile(catalogConfig.get(CatalogOptions.TABLE_PATTERN));
         List<String> allDatabase = catalog.listDatabases();
         allDatabase.removeIf(s -> !databasePattern.matcher(s).matches());
         for (String databaseName : allDatabase) {
             tableNames = catalog.listTables(databaseName);
             for (String tableName : tableNames) {
                 if (tablePattern.matcher(databaseName + "." + tableName).matches()) {
                     catalogTables.add(catalog.getTable(TablePath.of(databaseName, tableName)));
                 }
             }
         }
         return catalogTables;
     }
 }

```

### Compatibility
The code logic is incompatible with changes, and the existing Catalog implementations need to be changed. There is no change in user usage and it is compatible.

The following Catalog needs to be changed:

- ElasticSearch Catalog

- MySql Catalog

- SqlServerCatalog

- Star Rocks Catalog

- TiDB Catalog

### Task list

- #4529
- #4530 
- #4531 
- #4532 
- #4533

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
