### ISSUE TITLE
[Umbrella] [seatunnel-web] integration with airflow

### ISSUE THREAD

**Issue by dijiekstra** [apache/seatunnel#4538]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

integration with airflow 

### Task list

- [ ] job
   - [ ] define
   - [ ] execute
   - [ ] online
   - [ ] offline
   - [ ] delete
   - [ ] list
- [ ] task
   - [ ] kill
   - [ ] rerun
   - [ ] getLog
   - [ ] ...

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Hxssssss** [comment]
I want to participate in this feature development

**Comment by dijiekstra** [comment]
> I want to participate in this feature development

Ok. Welcome! Which part u want to join

**Comment by RayVs** [comment]
I want to participate in this feature development too!

**Comment by dijiekstra** [comment]
> I want to participate in this feature development too!

Ok. Welcome! Which part u want to join
