### ISSUE TITLE
[Umbrella][Feature][Connector-V2][Docs] Refactor connector-v2 docs using unified format

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#4572]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

According to #4544 , we will start refactor connector-v2 docs to improve user experience.

### Task list

- [x] Jdbc Connector - MySQL @zhilinli123 
- [x] Kafka Connector @MonsterChenzhuo 
- [x] Http Connector @MonsterChenzhuo 
- [x] Mongodb Connector @MonsterChenzhuo 
- [x] Clickhouse Connector @MonsterChenzhuo  
- [x] My Hours @TaoZex 
- [ ] Klaviyo @TaoZex 
- [ ] lemlist @TaoZex 
- [ ] Onesignal @TaoZex 
- [x] HDFS  @lightzhao 
- [ ] Hive @lightzhao
- [x] PostgreSQL @zhilinli123 
- [x] SQL Server Connector @zhangchengming601
- [ ] Redshift Connector @zhangchengming601
- [x] db2 @zhangchengming601 
- [ ] Paimon @MonsterChenzhuo 
- [ ] Hbase @MonsterChenzhuo 
- [ ] Assert @MonsterChenzhuo 
- [x] Console @MonsterChenzhuo 
- [x] Doris @Carl-Zhou-CN 
- [x] Hudi @Carl-Zhou-CN 
- [x] S3 @EricJoy2048 
- [x] LocalFile Source 
- [ ] LocalFile Sink
- [x] SFTP File Source
- [ ] SFTP File Sink
- [x] FTP File Source
- [ ] FTP File Sink
- [x] CosFile Source
- [ ] CosFile Sink
- [x] OssFile Source
- [ ] OssFile Sink
- [ ] redis @Carl-Zhou-CN 
- [x] Iceberg @Carl-Zhou-CN 
- [x] kudu @Carl-Zhou-CN 
- [X] FeiShu @ruanwenjun 
- [X] Slack @ruanwenjun 
- [x] IOTDB @liunaijie 
- [x] SqlServer CDC @zhilinli123 
- [x] FakeSource @zhilinli123
- [x] Socket @zhilinli123
- [x] RocketMq @zhilinli123
- [x] SelectDB-Cloud @TaoZex
- [x] StarRocks @TaoZex
- [x] JDBC Oracle @ic4y 
- [x] JDBC Kingbase @NickCodeJourney
- [x] Amazonsqs   @HaoXuAI

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhilinli123** [comment]
mysql documentation improvements please assign to me

**Comment by MonsterChenzhuo** [comment]
kafka documentation、http documentation、clickhouse documentation improvements please assign to me

**Comment by jiangzzwy** [comment]
kafka sink端的partition参数存在误导，用户会理解成为sink端的并行度，建议修改一下，因为kafka的Connector的sink端的配置存在误导
`sink {
  kafka {
      topic = "seatunnel"
      bootstrap.servers = "CentOS:9092"
      partition = 1
      format = json
      kafka.request.timeout.ms = 60000
      semantics = EXACTLY_ONCE
  }
}`
这里的partition是写入的分区，不是并行度，kafka文档的编写，也可以指定给我来完善

**Comment by TaoZex** [comment]
Please assign me the connector documentation related to the SaaS API

**Comment by EricJoy2048** [comment]
> Please assign me the connector documentation related to the SaaS API

Can you explain which specific connectors are they?

**Comment by TaoZex** [comment]
> > Please assign me the connector documentation related to the SaaS API
> 
> Can you explain which specific connectors are they?

Thanks. Please assign My Hours、Klaviyo、lemlist、Onesignal connector doc to me.

**Comment by lightzhao** [comment]
HDFS documentation、Hive documentation  improvements please assign to me

**Comment by TyrantLucifer** [comment]
Hi all, there are any progress on it?

**Comment by zhilinli123** [comment]
> Hi all, there are any progress on it?

Please help me with the final review of Mysql. It is basically finished
@TyrantLucifer

**Comment by zhilinli123** [comment]
PostgreSQL Connector Assign to me Thanks .

**Comment by zhangchengming601** [comment]
SQL Server documentation improvements please assign to me

**Comment by zhangchengming601** [comment]
Redshift documentation improvements please assign to me

**Comment by zhilinli123** [comment]
https://github.com/apache/incubator-seatunnel/pull/4590

**Comment by zhilinli123** [comment]
SqlServer : https://github.com/apache/incubator-seatunnel/pull/4721

**Comment by zhilinli123** [comment]
Template PR please refer to:#4590 
source document:https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md?plain=1 
sink document:https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Mysql.md?plain=1
CC @ALL @MonsterChenzhuo @TaoZex @lightzhao @zhangchengming601

**Comment by MonsterChenzhuo** [comment]
> ### Code of Conduct
> 
>     * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
> 
> 
> ### Search before asking
> 
>     * [x]  I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.
> 
> 
> ### Describe the proposal
> 
> According to #4544 , we will start refactor connector-v2 docs to improve user experience.
> ### Task list
> 
>     * [x]  Jdbc Connector - MySQL @zhilinli123
> 
>     * [ ]  Kafka Connector @MonsterChenzhuo
> 
>     * [ ]  Http Connector @MonsterChenzhuo
> 
>     * [x]  Mongodb Connector @MonsterChenzhuo
> 
>     * [ ]  Clickhouse Connector @MonsterChenzhuo
> 
>     * [ ]  My Hours @TaoZex
> 
>     * [ ]  Klaviyo @TaoZex
> 
>     * [ ]  lemlist @TaoZex
> 
>     * [ ]  Onesignal @TaoZex
> 
>     * [ ]  HDFS  @lightzhao
> 
>     * [ ]  Hive @lightzhao
> 
>     * [ ]  PostgreSQL @zhilinli123
> 
>     * [ ]  SQL Server Connector @zhangchengming601
> 
>     * [ ]  Redshift Connector @zhangchengming601
> 
> 
> ### Are you willing to submit PR?
> 
>     * [ ]  Yes I am willing to submit a PR!

**Comment by Carl-Zhou-CN** [comment]
I want to try Doris and Hudi

**Comment by MonsterChenzhuo** [comment]
Please assign  Paimon、hbase、Assert、Console to me.

**Comment by zhangchengming601** [comment]
Please assign db2,oceanbase to me.

**Comment by zhangchengming601** [comment]
Please assign db2 to me.

**Comment by Carl-Zhou-CN** [comment]
I want to try redis,iceberg and kudu

**Comment by liunaijie** [comment]
summary the status and the supported connector  


| name | updated | |  
| ---- | ---- | ---- |  
| AmazonDynamoDB | N | |  
| Assert | WIP | |  
| Cassandra | N | |  
| Clickhouse | WIP | | 
| Console | WIP | |  
| DataHub | N | |  
| DingTalk | N | |  
| Doris | WIP | |  
| Elasticsearch | N | |  
| Email | N | |  
| Fake | N | |  
| Google-firestore | N | |  
| Google-sheet | N | |  
| Hbase | WIP | |  
| Hive | WIP | |  
| Hudi | WIP | |  
| Iceberg | Y | |  
| influxdb | N | |  
| iotdb | Y | |  
| JDBC | Y |  |  
| Kafka | WIP | |  
| Kudu | WIP | |  
| maxcompute | N | |  
| Mongo | Y | |  
| neo4j | N | |  
| openmldb | N | |  
| paimon | WIP |  
| pulsar | N | |  
| rabbitmq | N | |  
| redis | WIP | |  
| rocketmq | N | |  
| s3-redshift | N | |  
| selectdb-cloud | Y | |  
| sentry | N | |  
| slack | Y | |  
| socket | N | |  
| starrocks | Y | |  
| tablestore | N | |  
| tdengine | N | |  
| ftp (file) | N | |  
| hdfs (file) | WIP | |  
| local file (file) | N | |  
| oss (file) | N | |  
| oss-jindo (file) | N | |  
| s3 (file) | WIP | |
| sftp (file) | N | |  
| http | Y | |  
| feishu (http) | Y | |  
| github (http) | N | |  
| gitlab (http) | N | |  
| jira (http) | N | |  
| klaviyo (http) | WIP | |  
| lemlist (http) | WIP | |  
| myhours (http) | Y | |  
| notion (http) | N |  
| onesignal (http) | WIP | |  
| persistiq (http) | N | |  
| wechat (http) | N | |  

CDC:

| name | updated | |    
| ---- | ---- | ---- |    
| mongo | N | |  
| mysql | N | |  
| sqlserver | N | |

**Comment by TaoZex** [comment]
Please assign starrocks and selected-cloud to me. I have submitted the pr.

**Comment by zhilinli123** [comment]
- [Oracle] https://github.com/apache/seatunnel/pull/5239 @ic4y  Done
- [Oss] https://github.com/apache/seatunnel/pull/5233 @Hisoka-X  open

**Comment by zhilinli123** [comment]
hi, how is the progress of Connector document? @lightzhao @Carl-Zhou-CN @zhangchengming601

**Comment by zhilinli123** [comment]
FakeSource, Socket ,RocketMQ Assign me

**Comment by zengqinchris** [comment]
> I want to try redis,iceberg and kudu

When can I test and use it sink to iceberg
