### ISSUE TITLE
[Umbrella] Catalog Doc

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#4726]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Add detailed documentation to the Catalog to facilitate the use of users and the development of developers.

# Apache SeaTunnel Catalog

Catalogs provide metadata such as databases, tables, and information needed to access data in databases or other storage engines.Catalogs provides a unified API for managing metadata, verifies connectivity, and makes metadata accessible to Sources, Sinks, and Web.

Catalog enables users to reference existing metadata in their data systems, and automatically maps them to SeaTunnel’s corresponding metadata. Catalog greatly simplifies steps required to get started with SeaTunnel with users’ existing system, and greatly enhanced user experiences.

### Initialization operations

Note: The catalog name is not currently used. It is expected to be provided to the web backend for saving and querying

```Java
public interface CatalogFactory extends Factory {
    String factoryIdentifier();

    OptionRule optionRule();

    Catalog createCatalog(String catalogName, ReadonlyConfig options);
}

public interface Catalog extends AutoCloseable {

    void open() throws CatalogException;

    void close() throws CatalogException;

}
```

### Database operations

```java
public interface Catalog extends AutoCloseable {
    // --------------------------------------------------------------------------------------------
    // database
    // --------------------------------------------------------------------------------------------
    
    String getDefaultDatabase() throws CatalogException;

    boolean databaseExists(String databaseName) throws CatalogException;

    List<String> listDatabases() throws CatalogException;
    
    void createDatabase(String databaseName, boolean ignoreIfExists)
            throws DatabaseAlreadyExistException, CatalogException;

    void dropDatabase(String databaseName, boolean ignoreIfNotExists)
            throws DatabaseNotExistException, CatalogException;
}
```

### Table operations

```java
public interface Catalog extends AutoCloseable {
    // --------------------------------------------------------------------------------------------
    // table
    // --------------------------------------------------------------------------------------------
    
    List<String> listTables(String databaseName) throws CatalogException, DatabaseNotExistException;

    boolean tableExists(TablePath tablePath) throws CatalogException;

    CatalogTable getTable(TablePath tablePath) throws CatalogException, TableNotExistException;

    void createTable(TablePath tablePath, CatalogTable table, boolean ignoreIfExists)
            throws TableAlreadyExistException, DatabaseNotExistException, CatalogException;

    void dropTable(TablePath tablePath, boolean ignoreIfNotExists)
            throws TableNotExistException, CatalogException;
}
```

# MySQL Catalog

## Usage of MySQL Catalog

| name             | type   | required | default value |
| ---------------- | ------ | -------- | ------------- |
| username         | String | Yes      | -             |
| password         | String | Yes      | -             |
| base-url         | String | Yes      | -             |
| table-names      | List   | No       | -             |
| database-pattern | String | No       | .*            |
| table-pattern    | String | No       | -             |

### username [String]

Name of the database to use when connecting to the database server.

### password [String]

Password to use when connecting to the database server.

### base-url [String]

URL has to be with database, like "jdbc:mysql://localhost:5432/db" or "jdbc:mysql://localhost:5432/db?useSSL=true"

### table-names [List]

List of table names of databases to capture. The table name needs to include the database name, for example: database_name.table_name

### database-pattern [String]

The database names RegEx of the database to capture.

### table-pattern [String]

The table names RegEx of the database to capture. The table name needs to include the database name, for example: `database_.*\\.table_.*`

## Conf File Configuration

```conf
[source/sink] {
	[connector-factory-id] {
		catalog {
		    factory = "MySQL"
			username = "test"
			password = "123456"
			base-url = "jdbc:mysql://localhost:5432/db"
			table-names = [
				"db.table"
			]
		}
	}
}
```

#### example

```
env {
    "job.mode"=STREAMING
    "job.name"="cdc_mysql_to_mysql"
    "checkpoint.interval"="2000"
    "custom_parameters"=""
}
source {
    MySQL-CDC {
        parallelism = 1
        catalog {
            factory = "MySQL"
            # By default, the catalog will use the option of the same name as the connector
        }
        username = "mysqluser"
        password = "mysqlpw"
        database-names = ["seatunnel-test"]
        table-pattern = "seatunnel-test\\.orders_\\d+"
        base-url = "jdbc:mysql://localhost:54508/seatunnel-test"
    }
}
sink {
    jdbc {
        url = "jdbc:mysql://localhost:4000/test"
        driver = "com.mysql.cj.jdbc.Driver"
        catalog {
            factory = "MySQL"
            username = "root"
        	password = ""
        	base-url = "jdbc:mysql://localhost:4000/test"
        	table-pattern = "seatunnel-test2\\.orders_\\d+"
        }
        user = "root"
        password = ""
        query = "insert into sink(age, name) values(?,?)"
    }
}
```

## Data Type Mapping

| [MySQL type](https://dev.mysql.com/doc/refman/8.0/en/data-types.html) | SeaTunnel SQL type |
| :----------------------------------------------------------- | :----------------- |
| `BIT` `TINYINT`                                              | `TINYINT`          |
| `SMALLINT` `TINYINT UNSIGNED`                                | `SMALLINT`         |
| `INT` `MEDIUMINT` `SMALLINT UNSIGNED` `MEDIUMINT UNSIGNED`   | `INT`              |
| `BIGINT` `INT UNSIGNED`                                      | `BIGINT`           |
| `BIGINT UNSIGNED`                                            | `DECIMAL(20, 0)`   |
| `BIGINT`                                                     | `BIGINT`           |
| `FLOAT`                                                      | `FLOAT`            |
| `DOUBLE` `DOUBLE PRECISION`                                  | `DOUBLE`           |
| `NUMERIC(p, s)` `DECIMAL(p, s)`                              | `DECIMAL(p, s)`    |
| `BOOLEAN` `TINYINT(1)`                                       | `BOOLEAN`          |
| `DATE`                                                       | `DATE`             |
| `TIME [(p)]`                                                 | `TIME `            |
| `DATETIME [(p)]` `TIMESTAMP`                                 | `TIMESTAMP`        |
| `CHAR(n)` `VARCHAR(n)` `TEXT`                                | `STRING`           |
| `BINARY` `VARBINARY` `BLOB`                                  | `BYTES`            |

### Task list

- 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
