### ISSUE TITLE
[Umbrella] [doc] refactor content of document structure 

### ISSUE THREAD

**Issue by mengfeiMonica** [apache/seatunnel#4753]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

In order for users to learn more about Seatunnel's documentation, we need to update the current documentation to fill in the missing documentation. We need to build together!

### Task list

About document specifications: 

- Capitalize the first letter of all words in the first-level directory; 
- Capitalize the first word of the secondary directory; 
- Capitalize the first word of the tertiary directory;

About document structure：
<img width="1151" alt="image" src="https://github.com/apache/incubator-seatunnel/assets/84299258/4a56eaa9-ba53-45ed-849e-09297b69f41e">

Contributions about the content of the document：

- relate PR link [https://github.com/apache/incubator-seatunnel/pull/4730]

There are the following documentation content that needs to be supplemented (need to be co-created by contributors)：

- Connector documentation updates
- More FAQ
- More user use cases
- Other supplements

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
