### ISSUE TITLE
[STIP-17] The Sink terminal implements SaveMode functions (including SchemaSaveMode and DataSaveMode)

### ISSUE THREAD

**Issue by chl-wxp** [apache/seatunnel#5390]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Design documentation
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=263427916

### Description

    saveMode stands for save mode, and the purpose is to process the table structure and existing data at the target end before synchronizing the task.
    saveMode is divided into two types: existing table structure saveMode and existing data saveMode.
    SchemaSaveMode：
        RECREATE_SCHEMA ：Will create when the table does not exist, delete and rebuild when the table is saved        
        CREATE_SCHEMA_WHEN_NOT_EXIST ：Will Created when the table does not exist, skipped when the table is saved        
        ERROR_WHEN_SCHEMA_NOT_EXIST ：Error will be reported when the table does not exist
    DataSaveMode：
       DROP_DATA： Preserve database structure and delete data
       APPEND_DATA：Preserve database structure, preserve data
       CUSTOM_PROCESSING：User defined processing
       ERROR_WHEN_DATA_EXISTS：When there is data, an error is reported

### Task list
- [ ] Jdbc Connector Sink @chl-wxp 
- [ ] JDBC DB2 Sink
- [ ] S3-redshift Connector Sink @chl-wxp 
- [ ] Iceberg Connector Sink @ic4y 
- [ ] StarRocks Connector Sink @chl-wxp 
- [ ] SelectDB Connector Sink @ic4y 
- [ ] Mongodb Connector Sink @ic4y 
- [ ] ES Connector Sink @chl-wxp 
- [ ] Kafka Connector Sink @chl-wxp 
- [ ] S3 Connector Sink @chl-wxp 
- [ ] doris Connector Sink  @gnehil
- [ ] hive  Connector Sink  @liunaijie 
- [ ] iotdb Connector Sink 
- [ ] hbase Connector Sink 
- [ ] redis Connector Sink @zhibinF 
- [ ] rocket Connector Sink 
- [ ] influxdb Connector Sink
- [ ] Paimon Connector Sink @Carl-Zhou-CN 
- [ ] Snowflake Connector Sink @HaoXuAI 
- [ ] Maxcompute Connector Sink 
- [ ] ClickHouse Connector Sink  @liunaijie
- [ ] ftp Connector Sink @Japson0 

 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhibinF** [comment]
I am willing to submit a PR about redis Connector Sink.

**Comment by EricJoy2048** [comment]
@chl-wxp  Can you add an example for this feature?

**Comment by liunaijie** [comment]
pls assign hive, clickhouse to me.
And is there have basic code branch? @chl-wxp

**Comment by EricJoy2048** [comment]
> pls assign hive, clickhouse to me. And is there have basic code branch? @chl-wxp

Assign Hive, Clickhouse to you.

**Comment by Japson0** [comment]
assign ftp to me
