### ISSUE TITLE
[STIP-18] [Feature][Connector][Zeta] Sink supports multi-table in one task

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#5395]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support supports multi-table in one sink task to save resource and speed up.

STIP: https://cwiki.apache.org/confluence/display/SEATUNNEL/STIP3-Sink+supports+multi-table+in+one+task

### Task

- [x] #5604 
- [x] #5620

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
