### ISSUE TITLE
[Umbrella][Improve][CommonError] Replace `CommonErrorCodeDeprecated.JSON_OPERATION_FAILED`

### ISSUE THREAD

**Issue by CheneyYin** [apache/seatunnel#5945]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

PR #5793 introduce new error define rule. Now it is necessary to follow up and refactor some ErrorCode. This PR will refactor `JSON_OPERATION_FAILED` and adjust the code related.

### Task list

- [x] Replace `JSON_OPERATION_FAILED`
  - [x] #5919 
  - [x] #5948
  - [x] #5978

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
