### ISSUE TITLE
[Feature][zeta log] Use jobid and pipelineid as the trace id for log tracking.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#6148]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/MDC.html

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
@liugddx   I want to try it
