### ISSUE TITLE
[Roadmap][Volunteer-Wanted] SeaTunnel 2.0 Roadmap Task

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#720]
Hello community, we have recently made a 2.0 roadmap, welcome everyone to discuss and supplement.

**Update some latest messages:**
Hi guys, this is the roadmap draft according to the mindmap, for the following 3 months, please feel free to share your ideas and welcome to contribute to SeaTunnel and join the community.

Roadmap for 12/2021 ~ 03/2022:

- [ ] Official website construction
  - [x] offical website @wolfboys 
  - [x] #1146
  - [x] #980
- [x] Project Structure @simon824 
  - [x] Refine module, codes structure #775 #824
- [ ] Core Framework
  - [ ] execution
    - [ ] #962
  - [ ] Connectors Plugin Framework
    - [x]  refine plugin Framework related codes and APIs（due to breaking changes from spark2.x to spark3.x, whereas flink1.9 to flink1.14）
    - [ ] Multi-Version Plugin Dependency with Java ClassLoader @wntp #823 
    - [ ] Do not package in a assembly jar (for multi-version plugins) to avoid Plugin Dependency override @CalvinKirs 
    - [ ] #963
    - [ ] auto-generate docs from plugin implementation code, especially from config.
    - [ ] (if possible) write once connector, can run both in spark and flink
  - [ ] Flink Backend Integration
    - [x] #788
    - [ ] #871
    - [x] #868 
  - [ ] Spark Backend Integration
    - [ ] #875
  - [ ] Configuration Management Framework
    - [x] replace typesafe config as pom dependency, other than copying codes to SeaTunnel codebase @leo65535 #903   #906 
    - [ ] ability to define variables @simon824 
    - [x] #964
- [x] Code Quality & Developer Cooperation #
  - [x] add CI to SeaTunnel codebase on github  #708 #777 #677 #673 
  - [x] add codestyle check #714 
  - [x] Change Scala to Java as the main program language
  - [ ] force check pull request title and commit log starting with issue id, such as '[ISSUE-194] xxx', just like flink community.
- [ ] plugins @wuchunfu @wolfboys @simon824 
  - [ ] add more sources: Hive, Clickhouse, Elasticsearch, MongDB(CDC), Kafka, HDFS,Druid
  - [ ] add more sink: Hive, Clickhouse, Elasticsearch, Kafka, HDFS
  - [ ] add more transform: ?
  - [x] #1062
  - [x] #1063
  - [x] #1064 
  - [x] #1065 
  - [x] #1066 
  - [x] #1038 
  - [ ] #1039
  - [x] #816 
  - [x] #773 
  - [x] #752 
  - [x] #740 
  - [x] #692 
  - [x] #809 
  - [x] #923 
  - [x] #920 
  - [x] #911 
- [x] Installation & Deployment @kezhenxu94 #815 
  - [ ] refine start-seatunnel.sh related codes to give more convenience for SeaTunnel job management(install, deploy, undeploy..)
  - [x] support install and try SeaTunnel by docker container.

**Comment by leo65535** [comment]
The roadmap 2.0 is excellent 👍.

I want to add a new feature to roadmap, it is very important for data integration.

This point of this feature is introduce a new workflow template, show you the workflow demo.

**The origin workflow**
```
env {
  execution.parallelism = 1
}

source {
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}

transform {
    sql {
      sql = "select name,age from fake"
    }
}

sink {
  ConsoleSink {}
}
```

**The feature workflow**
```
CREATE TABLE fake_source (
  name string,
  age int
) with (
  'connector.type' = 'fakestream',
  'format.type' = 'json'
);

CREATE TABLE print_sink (
  name string,
  age int
) with (
  'connector.type' = 'print',
);

INSERT INTO print_sink
SELECT * FROM fake_source;
```

**Comment by wntp** [comment]
The roadmap 2.0 is excellent 👍.
I wanted After Process and Per Process of source/sink/transform is also in, Let's do it together, come on!

**Comment by timothy65535** [comment]
The roadmap 2.0 is excellent 👍.

**Comment by kalencaya** [comment]
The roadmap 2.0 is excellent 👍.
Configurable is programmable, why not provide useful config dsl assemble source、transform、sink?

**Comment by chenhu** [comment]
The roadmap 2.0 is excellent 👍
The new configuration is easier to accept .

**Comment by chenhu** [comment]
We could add the scheduler info like this :
CREATE TABLE fake_source (
  name string,
  age int
) with (
  'connector.type' = 'fakestream',
  'format.type' = 'json'
  **’scheduler.cron' = '* * * * *'**
);

CREATE TABLE print_sink (
  name string,
  age int
) with (
  'connector.type' = 'print',
);

INSERT INTO print_sink
SELECT * FROM fake_source;

**Comment by garyelephant** [comment]
Hi all, we have announced the roadmap for the following 3 months, please feel free to contribute to SeaTunnel and contact us.

Roadmap for 12/2021 ~ 03/2022:

- [ ] Project Structure
  - [ ] Refine module, codes structure
    - [ ] move all plugin modules to plugins/ submodule
- [ ] Core Framework
  - [ ] Flink Backend Integration
    - [ ] support latest version of Flink
    - [ ] refine the codes to support integrate with Flink Connector with *Zero* coding
  - [ ] Spark Backend Integration
    - [ ] support latest version of Flink
    - [ ] refine the codes to support integrate with Spark Connector with *Zero* coding
  - [ ] Plugin Framework
    - [ ]  refine plugin Framework related codes
    - [ ] Multi-Version Plugin Dependency with Java ClassLoader
    - [ ] Do not package in a assembly jar (for multi-version plugins) to avoid Plugin Dependency override
    - [ ] support CDC in framework
- [ ] Configuration Management Framework
  - [ ] replace typesafe config as pom dependency, other than copying codes to SeaTunnel codebase
  - [ ] ability to define variables
- [ ] Code Quality & Developer Cooperation
  - [ ] add CI to SeaTunnel codebase on github
  - [ ] add codestyle check
- [ ] plugins
  - [ ] add more sources: ?
  - [ ] add more sink: ?
  - [ ] add more transform: ?
- [ ] Installation & Deployment
  - [ ] refine start-seatunnel.sh related codes to give more convenience for SeaTunnel job management(install, deploy, undeploy..)
  - [ ] support install and try SeaTunnel by docker container.

**Comment by wolfboys** [comment]
I want to contribute to the `Core Framework` and `Plugin Framework` part, I am interested in `Flink Backend Integration` and `Plugin Framework`, I have relevant implementation experience.

**Comment by dailidong** [comment]
> I want to contribute to the `Core Framework` and `Plugin Framework` part, I am interested in `Flink Backend Integration` and `Plugin Framework`, I have relevant implementation experience.

good job, Do you want to implement the entire parts of `Flink Backend Integration` and `Plugin Framework`?

**Comment by dailidong** [comment]
> Hi all, we have announced the roadmap according to the mindmap, for the following 3 months, please feel free to contribute to SeaTunnel and contact us.
> 
> Roadmap for 12/2021 ~ 03/2022:
> 
> * [ ]  Project Structure
>   
>   * [ ]  Refine module, codes structure
>     
>     * [ ]  move all plugin modules to plugins/ submodule
> * [ ]  Core Framework
>   
>   * [x]  Flink Backend Integration
>     
>     * [ ]  support latest version of Flink 1.14
>     * [ ]  refine the codes to support integrate with Flink Connector with _Zero_ coding
>   * [ ]  Spark Backend Integration
>     
>     * [ ]  support latest version of Spark 3.2.0
>     * [ ]  refine the codes to support integrate with Spark Connector with _Zero_ coding
>   * [x]  Plugin Framework
>     
>     * [ ]   refine plugin Framework related codes
>     * [ ]  Multi-Version Plugin Dependency with Java ClassLoader
>     * [ ]  Do not package in a assembly jar (for multi-version plugins) to avoid Plugin Dependency override
>     * [ ]  support CDC in framework
> * [ ]  Configuration Management Framework
>   
>   * [ ]  replace typesafe config as pom dependency, other than copying codes to SeaTunnel codebase
>   * [ ]  ability to define variables
>   * [ ]  consider to support SQL as another configuration DSL.
> * [ ]  Code Quality & Developer Cooperation
>   
>   * [ ]  add CI to SeaTunnel codebase on github
>   * [ ]  add codestyle check
> * [ ]  plugins
>   
>   * [ ]  add more sources: Hive, Clickhouse, Elasticsearch, MongDB(CDC), Kafka, HDFS
>   * [ ]  add more sink: Hive, Clickhouse, Elasticsearch, Kafka, HDFS
>   * [ ]  add more transform: ?
> * [ ]  Installation & Deployment
>   
>   * [ ]  refine start-seatunnel.sh related codes to give more convenience for SeaTunnel job management(install, deploy, undeploy..)
>   * [ ]  support install and try SeaTunnel by docker container.

good news.

**Comment by dailidong** [comment]
Everyone is welcome to share your opinions and suggestions if you have any suggestions about the roadmap, welcome to join the open source community, thx

**Comment by wuchunfu** [comment]
I want to contribute to the `plugins` part, I am interested in `plugins`.

**Comment by simon824** [comment]
I can contribute `Project Structure `,`Plugins`,`ability to define variables`

**Comment by dailidong** [comment]
@wolfboys @wuchunfu  @simon824 
good,  I have updated to the related info to the content, thx `https://github.com/InterestingLab/seatunnel/issues/720#issuecomment-991480070`

**Comment by wntp** [comment]
@garyelephant @dailidong hi,I want to contribute to the “Multi-Version Plugin Dependency with Java ClassLoader” part

**Comment by dailidong** [comment]
> @garyelephant @dailidong hi,I want to contribute to the “Multi-Version Plugin Dependency with Java ClassLoader” part

done, thx

**Comment by wolfboys** [comment]
> 

👌

**Comment by wolfboys** [comment]
> @wolfboys @wuchunfu @simon824 good, I have updated to the related info to the content, thx please take a look, [Roadmap Tasks](https://github.com/InterestingLab/seatunnel/issues/720#issuecomment-991480070)

👌🏻

**Comment by dailidong** [comment]
hi all,
We plan to start a community meeting at 20:00 on December 16 (UTC +8). We have established a list of topics to be discussed on google docs. Welcome everyone to list the issues you want to discuss in advance. The content of the topics is arbitrary, but you need to advance Create ISSUE, follow-up I will synchronize the relevant discussion process and results to ISSUE, and finally categorize it on the wiki

https://docs.google.com/document/d/1bXyZGt0g8f8_-d9Oj7oMx9BdWSjf8oJYZgNmoEooj8I/edit?usp=sharing

**Comment by dailidong** [comment]
> Hi guys, this is the roadmap draft according to the mindmap, for the following 3 months, please feel free to share your ideas and welcome to contribute to SeaTunnel and join the community.
> 
> Roadmap for 12/2021 ~ 03/2022:
> 
> * [ ]  Official website construction
> * [ ]  Project Structure @simon824
>   
>   * [ ]  Refine module, codes structure
>     
>     * [ ]  move all plugin modules to plugins/ submodule
> * [ ]  Core Framework
>   
>   * [x]  Flink Backend Integration
>     
>     * [ ]  support latest version of Flink 1.14
>     * [ ]  refine the codes to support integrate with Flink Connector with _Zero_ coding
>   * [ ]  Spark Backend Integration
>     
>     * [ ]  support latest version of Spark 3.2.0
>     * [ ]  refine the codes to support integrate with Spark Connector with _Zero_ coding
>   * [x]  Plugin Framework
>     
>     * [ ]   refine plugin Framework related codes
>     * [x]  Multi-Version Plugin Dependency with Java ClassLoader @wntp
>     * [ ]  Do not package in a assembly jar (for multi-version plugins) to avoid Plugin Dependency override @CalvinKirs
>     * [ ]  support CDC in framework
> * [ ]  Configuration Management Framework
>   
>   * [ ]  replace typesafe config as pom dependency, other than copying codes to SeaTunnel codebase @CalvinKirs
>   * [x]  ability to define variables @simon824
>   * [ ]  consider to support SQL as another configuration DSL.
> * [ ]  Code Quality & Developer Cooperation
>   
>   * [x]  add CI to SeaTunnel codebase on github
>   * [x]  add codestyle check
> * [ ]  plugins @wuchunfu @wolfboys @simon824
>   
>   * [ ]  add more sources: Hive, Clickhouse, Elasticsearch, MongDB(CDC), Kafka, HDFS
>   * [ ]  add more sink: Hive, Clickhouse, Elasticsearch, Kafka, HDFS
>   * [ ]  add more transform: ?
> * [ ]  Installation & Deployment @kezhenxu94
>   
>   * [ ]  refine start-seatunnel.sh related codes to give more convenience for SeaTunnel job management(install, deploy, undeploy..)
>   * [ ]  support install and try SeaTunnel by docker container.
> * [ ]  Change Scala to Java as the main program language

hi gary, I will update these contents to the first comment to make more users easily to see the Roadmap draft

**Comment by calvinjiang** [comment]
I'm mainly interested in the Flink Backend Integration.  I'd like to contribute more features for this.

**Comment by kezhenxu94** [comment]
- [ ] support install and try SeaTunnel by docker container.

This one is finished in #815

**Comment by dailidong** [comment]
> I'm mainly interested in the Flink Backend Integration. I'd like to contribute more features for this.

good job, please create an related issue first

**Comment by xbkaishui** [comment]
> The roadmap 2.0 is excellent 👍.
> 
> I want to add a new feature to roadmap, it is very important for data integration. We use flume long long ago, but it's not friendly for us to write the agent file. Then we use flinksql replace the flume, it have provided great convenience to insert、etl data, etc.
> 
> project	weakness
> flume	1) need to learn how to write agent file 2) can not work with resource manager like yarn, k8s
> sqoop	1) don't have rich connectors 2) based on mapreduce
> ### flinksql
> * has rich connectors, cdc
> * friendly for us, we can use sql grammar easily, like `+`, `-`, etc
> * easy to work with resource manager, yarn, k8s
> 
> This point of this feature is introduce a new workflow template, show you the workflow demo.
> 
> **The origin workflow**
> 
> ```
> env {
>   execution.parallelism = 1
> }
> 
> source {
>     FakeSourceStream {
>       result_table_name = "fake"
>       field_name = "name,age"
>     }
> }
> 
> transform {
>     sql {
>       sql = "select name,age from fake"
>     }
> }
> 
> sink {
>   ConsoleSink {}
> }
> ```
> 
> **The feature workflow**
> 
> ```
> CREATE TABLE fake_source (
>   name string,
>   age int
> ) with (
>   'connector.type' = 'fakestream',
>   'format.type' = 'json'
> );
> 
> CREATE TABLE print_sink (
>   name string,
>   age int
> ) with (
>   'connector.type' = 'print',
> );
> 
> INSERT INTO print_sink
> SELECT * FROM fake_source;
> ```

that's awesome, sql is common language for use.

**Comment by dailidong** [comment]
if anybody who want to do some contributions, please leave a message.

**Comment by yuangjiang** [comment]
the roadmap 2.0 
It is recommended to disassemble flink into two different execution modes. From the current test, the flink datastream api and table api cannot be unified. Then we need to support the sql connector that can be submitted to the community. The plug-ins that have been developed by themselves are not two Different modes of execution

**Comment by yuangjiang** [comment]
It is recommended to support the submission of spark and flink scripts. The plugin can be used to submit the extended data of spark hive.

**Comment by BruceWong96** [comment]
I want to contribute to the Plugin Framework part, I am interested in Flink Backend Integration and Plugin Framework, I have relevant implementation experience.

**Comment by Yves-yuan** [comment]
The roadmap 2.0 is excellent 👍
I'm interested in [Flink Backend Integration],[Configuration Management Framework] and [plugins] modules,and i will try to make some contributions.

**Comment by ZhangchengHu0923** [comment]
The roadmap 2.0 is excellent 👍
I'd like to try https://github.com/apache/incubator-seatunnel/issues/1062
@dailidong
