### ISSUE TITLE
[STIP-20] [Umbrella] CDC DDL Sync Design(Zeta)

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7930]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

# Backgroud
Currently, we have support for data change capture(CDC #3175), but no further design for schema evolution.
- MySQL
- Oracle
- Postgres
- SQlServer
- ...

And as CDC data synchronization, I think we need to support schema evolution(DDL)  as a feature, and I want to hear from you all how you think it can be implemented in SeaTunnel.

# Motivation
- Support read database ddl sql (mysql/oracle/...)
- Support ddl sync to any sink（Standardized parse ddl to event）
- Support pause and resume ddl at any time
- Support automatic processing of old data and new data switche 

# Overall Design

## Basic flow
![image](https://github.com/user-attachments/assets/aa3c661a-76e0-4e9e-bc15-28426af0276d)

- Depends on checkpoint to push ddl: reader -> writer -> committer

## Phase1 - Before Change

![image](https://github.com/user-attachments/assets/3b749c11-fc7a-4cb9-a3d7-d4370e06112c)

- Data flow mixed with structure flow
- DDL is bound to database syntax

## Phase2 - Starting Change

![image](https://github.com/user-attachments/assets/9dd29422-460e-402d-944f-af01a7c13d50)

- Parsed ddl into schema events

## Phase3 - Splitting data flow and structure flow

![image](https://github.com/user-attachments/assets/686568aa-3685-4864-af6d-34feeceed3cd)

- Insert checkpoint signals before and after ddl
    - `schema-change-before` signals
    - `schema-change-after` signals

## Phase4 - Handling `schema-change-before` signal

![image](https://github.com/user-attachments/assets/f7cc88a3-553d-46dd-afb7-4f03cf335519)

- Stop source read data
- Waiting for all old data refresh to sink storage

## Phase5 - Execute ddl into source & sink

![image](https://github.com/user-attachments/assets/fe5b7549-b497-484c-96c9-18fb0066ce70)

- Stop checkpoint manager

## Phase6 - Handling `schema-change-after` signal

![image](https://github.com/user-attachments/assets/7ee323fa-9e7b-48f9-ae2c-a0f8ff5aba7a)

## Phase7 - Completed

![image](https://github.com/user-attachments/assets/4a720ce7-44bd-43cf-943d-0bb34529146c)

- Restart checkpoint manager
- Restart read data for source

### Task list

- [x] https://github.com/apache/seatunnel/pull/5125
- [x] https://github.com/apache/seatunnel/pull/7463
- [x] https://github.com/apache/seatunnel/pull/6929
- [x] https://github.com/apache/seatunnel/pull/7908

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by hailin0** [comment]
link https://github.com/apache/seatunnel/issues/3175

**Comment by Carl-Zhou-CN** [comment]
Niubility awesome

**Comment by dailai** [comment]
> Niubility awesome

Haha, is not convinced？

**Comment by dailai** [comment]
> Niubility awesome

+1

**Comment by Carl-Zhou-CN** [comment]
> > Niubility awesome
> 
> +1

Ha ha, you learned

**Comment by pinsisong** [comment]
Oracle-CDC 
schema-changes.enabled = true
Oracle重做日志会频繁切换，导致归档日志巨大。
如何解决？
